# This is a basic workflow to help you get started with Actions

name: test

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test dc 1
    steps:
      # To use this repository's private action, you must check out the repository
      - name: test_CI_CD
        uses: actions/checkout@master
      - name: test build dc
        uses: ./ # Uses an action in the root directory
        id: test
      
      - name: Get the output time
        run: echo "The time was ${{ steps.test.outputs.time }}"

  build_and_pub:
    
    needs: [test_job]
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: push
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PWD }}  ${{ secrets.DOCKER_NAME }}
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to registry
        run: docker push ${{ secrets.DOCKER_NAME }}/test_image
 
 
 
 
 
       # uses: docker/build-push-action@v1
       # with:
       #   username: ${{ secrets.DOCKER_LOGIN }}
       #   password: ${{ secrets.DOCKER_PWD }}
       #   registry: ${{ secrets.DOCKER_NAME }}
       #   repository: test_image
       #   tags: v1
            
